[package]
name = "lang"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.17.1"
pyo3 = { version = "0.27.2", features = ["auto-initialize"] }
rand = "0.8"
miette = { version = "7.2.0", features = ["fancy"] }
thiserror = "1.0"
